name: GitHub Actions - Testing Comments on PRs
on:
  # Trigger the workflow on push or pull request
  pull_request:
    types:
      - opened
    branches:
      - main
      - develop
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for contributing!'
            })
